function A = V4_medians_and_cis(upper_ci_level,lower_ci_level,sequence)

% this function calculates the median and upper and lower
% cis of a time sequence generated by a GEM. This
% only works for sequences that occur at a set of standardized times.

dimensions = size(sequence); % find how many rows, etc.
A = nan(3,dimensions(2),dimensions(1)); % pre-allocate

for i = 1:dimensions(1) % dimension one is number of states
    A(1,:,i) = prctile(sequence(i,:,:),lower_ci_level,3);
    A(2,:,i) = prctile(sequence(i,:,:),50,3);
    A(3,:,i) = prctile(sequence(i,:,:),upper_ci_level,3);
end
