# This script uses the trait value .csvs generated by the Matlab simulation code
### to plot the relationship between the median max birth rates of the two competitors
### at the final time step of the simulation (Figure 5 of the main text).
# This script also uses the abundance .csvs generated by the Matlab simulation
### to visualize this relationship as a function of the final abundance of the focal
### competitors' abundance.

#### Required Packages #### 
library(ggplot2)

#### Begin with simulations initialized with abundances below the unstable equil. ####
# load .csvs -- make sure these relative paths point to the file's current location.
traits_i = read.csv("/data/traits_i_j3_below.csv")
traits_j = read.csv("/data/traits_j_j3_below.csv")
abundances_i = read.csv("/data/abundances_i_j3_below.csv")

# These are in wide format from Matlab.
str(traits_i)
# Only need the trait values at the final time, which are in the final column.
# But need all replicates, each of which is a row.
traits_i[,ncol(traits_i)] # this will work.
# check that the structure of the abundance file is the same.
str(abundances_i) # it is.

# Create empty dataframe to store final trait values for each replicate,
# along with the abundance of population i at 
# (1) the final time where both are present w/ non-missing trait values (abundances_i_atTrait),
# (2) the final simulation time, tmax (abundances_i_atTmax)
# (3) whether either competitor is extinct at tmax (extinction_ij)
# (4) the time at which an extinction occurred, where applicable (ext_time_ij)
dat <- data.frame(trait_i = rep(NA, length = nrow(traits_i)),
                 trait_j = rep(NA, length = nrow(traits_j)),
                 abundances_i_atTrait = rep(NA, length = nrow(traits_i)), 
                 abundances_i_atTmax = abundances_i[,ncol(abundances_i)], # fill in with final pop i abundance
                 extinction_ij = rep(0, length = nrow(abundances_i)),
                 ext_time_ij = rep(">1200", length = nrow(abundances_i))) # initialize w/ right-censored time value, overwrite in loop below
dat$abundances_i_atTmax[which(is.na(dat$abundances_i_atTmax))] <- 0 # overwrite NA final values with 0s to include these replicates when plotting.

# loop over replicates (rows in .csvs)...
for (ii in 1:nrow(abundances_i)){
   # if one pop is extinct at tmax, final trait values will be NAs...
  if (is.na(traits_i[ii,ncol(traits_i)]) | is.na(traits_j[ii,ncol(traits_j)])){
    # store last trait value
    dat$trait_i[ii] = traits_i[ii, which(is.na(traits_i[ii,]) | is.na(traits_j[ii,]))[1]-1] 
    # store corresponding trait for competitor
    dat$trait_j[ii] = traits_j[ii, which(is.na(traits_i[ii,]) | is.na(traits_j[ii,]))[1]-1] 
    # store competitor abundances from this last time point where both are present
    dat$abundances_i_atTrait[ii] = abundances_i[ii, which(is.na(traits_i[ii,]) | is.na(traits_j[ii,]))[1]-1] 
    # set extinction for this rep to 1
    dat$extinction_ij[ii] = 1 
    # store value of last time step with non-zero abundances of both competitors
    dat$ext_time_ij[ii] = which(is.na(traits_i[ii,]) | is.na(traits_j[ii,]))[1]-1
  }
  # if they both persist....
  if (!is.na(traits_i[ii,ncol(traits_i)]) & !is.na(traits_j[ii,ncol(traits_j)])){
    # store last trait value
    dat$trait_i[ii] = traits_i[ii, ncol(traits_i)]
    # store corresponding trait for competitor
    dat$trait_j[ii] = traits_j[ii, ncol(traits_j)] 
    # store corresponding final abundances
    dat$abundances_i_atTrait[ii] = abundances_i[ii, ncol(traits_i)]
    # Do not need to overwrite dat$extinction_ij[ii] because is initialized as "0"
    # Do not need to overwrite dat$extinction_time_ij[ii] because is initialized as right-censored max time
  }
}

# Plot final trait values against each other, 
### colored by final abundances where both competitors are present,
### facet wrapped by whether one competitor was extinct (Y/N) by tmax. ##
quartz(height = 4, width = 8) # doesn't work with windows
ggplot(dat, aes(x = trait_i, y = trait_j, color = abundances_i_atTmax)) +
  geom_point() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        aspect.ratio = 1) +
  ylab("Median maximum birth rate of\n competitor population") +
  xlab("Median maximum birth rate of\n focal population") +
  labs(color = "Focal population\nabundance at tmax") +
  facet_wrap(~extinction_ij, 
             labeller = labeller(extinction_ij = c("0" = "Neither Extinct",
                                                   "1" = "Focal or Competitor Extinct"))) +
  ylim(0, 0.35) +
  xlim(0, 0.35) +
  geom_hline(yintercept= 0.25, lty = 2) + geom_vline(xintercept= 0.25, lty = 2)


#### For trials initially at the unstable equilibrium ####
# load .csvs -- make sure these relative paths point to the file's current location.
traits_i_at = read.csv("/data/traits_i_j3_at.csv")
traits_j_at = read.csv("/data/traits_j_j3_at.csv")
abundances_i_at = read.csv("/data/abundances_i_j3_at.csv")

# check that structures are the same
str(traits_i_at)
traits_i_at[,ncol(traits_i_at)]
str(abundances_i_at)

# create new dataframe to hold trait values, abundances, extinctions, and time to extinctions
dat_at <- data.frame(trait_i = rep(NA, length = nrow(traits_i_at)),
                 trait_j = rep(NA, length = nrow(traits_j_at)),
                 abundances_i_atTrait = rep(NA, length = nrow(traits_i_at)),
                 abundances_i_atTmax = abundances_i_at[,ncol(abundances_i_at)],
                 extinction_ij = rep(0, length = nrow(abundances_i_at)),
                 ext_time_ij = rep(">1200", length = nrow(abundances_i_at)))
dat_at$abundances_i_atTmax[which(is.na(dat_at$abundances_i_atTmax))] <- 0 # overwrite NA final values with 0s to include these replicates when plotting.

# loop over replicates...
for (ii in 1:nrow(abundances_i_at)){
   # if one pop is NA at tmax...
  if (is.na(traits_i_at[ii,ncol(traits_i_at)]) | is.na(traits_j_at[ii,ncol(traits_j_at)])){
    dat_at$trait_i[ii] = traits_i_at[ii, which(is.na(traits_i_at[ii,]) | is.na(traits_j_at[ii,]))[1]-1]
    dat_at$trait_j[ii] = traits_j_at[ii, which(is.na(traits_i_at[ii,]) | is.na(traits_j_at[ii,]))[1]-1]
    dat_at$abundances_i_atTrait[ii] = abundances_i_at[ii, which(is.na(traits_i_at[ii,]) | is.na(traits_j_at[ii,]))[1]-1]
    dat_at$extinction_ij[ii] = 1 # set extinction for this rep to 1
    dat_at$ext_time_ij[ii] = which(is.na(traits_i_at[ii,]) | is.na(traits_j_at[ii,]))[1]-1
    
  }
  # if they both persist....
  if (!is.na(traits_i_at[ii,ncol(traits_i_at)]) & !is.na(traits_j_at[ii,ncol(traits_j_at)])){
    dat_at$trait_i[ii] = traits_i_at[ii, ncol(traits_i_at)] # store last trait value
    dat_at$trait_j[ii] = traits_j_at[ii, ncol(traits_j_at)] # store corresponding trait for competitor
    dat_at$abundances_i_atTrait[ii] = abundances_i_at[ii, ncol(traits_i_at)]
  }
}

# check
dat_at
names(dat_at)

# Plot final trait values against each other, 
### colored by final abundances where both competitors are present,
### facet wrapped by whether one competitor was extinct (Y/N) by tmax. ##
quartz(height = 4, width = 8) # doesn't work with windows
ggplot(dat_at, aes(x = trait_i, y = trait_j, color = abundances_i_atTmax)) +
  geom_point() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        aspect.ratio = 1) +
  ylab("Median maximum birth rate of\n competitor population") +
  xlab("Median maximum birth rate of\n focal population") +
  labs(color = "Focal population\nabundance at tmax") +
  facet_wrap(~extinction_ij, 
             labeller = labeller(extinction_ij = c("0" = "Neither Extinct",
                                                   "1" = "Focal or Competitor Extinct"))) +
  ylim(0, 0.35) +
  xlim(0, 0.35) +
  geom_hline(yintercept= 0.25, lty = 2) + geom_vline(xintercept= 0.25, lty = 2)


#### For replicates starting above the unstable equilibrium ####
# load .csvs -- make sure these relative paths point to the file's current location.
traits_i_above = read.csv("/data/traits_i_j3_above.csv")
traits_j_above = read.csv("/data/traits_j_j3_above.csv")
abundances_i_above = read.csv("/data/abundances_i_j3_above.csv")

# check that structures are the same
str(traits_i_above)
traits_i_at[,ncol(traits_i_above)]
str(abundances_i_above)

# create new dataframe to hold trait values, abundances, extinctions, and time to extinctions
dat_above <- data.frame(trait_i = rep(NA, length = nrow(traits_i_above)),
                 trait_j = rep(NA, length = nrow(traits_j_above)),
                 abundances_i_atTrait = rep(NA, length = nrow(traits_i_above)), 
                 abundances_i_atTmax = abundances_i_above[,ncol(abundances_i_above)], # fill in with final values
                 extinction_ij = rep(0, length = nrow(abundances_i_above)),
                 ext_time_ij = rep(">1200", length = nrow(abundances_i_above)))
dat_above$abundances_i_atTmax[which(is.na(dat_above$abundances_i_atTmax))] <- 0 # overwrite NA final values with 0s to include these replicates when plotting.

for (ii in 1:nrow(abundances_i_above)){
   # if one pop is NA at tmax...
  if (is.na(traits_i_above[ii,ncol(traits_i_above)]) | is.na(traits_j_above[ii,ncol(traits_j_above)])){
    dat_above$trait_i[ii] = traits_i_above[ii, which(is.na(traits_i_above[ii,]) | is.na(traits_j_above[ii,]))[1]-1] # store last trait value
    dat_above$trait_j[ii] = traits_j_above[ii, which(is.na(traits_i_above[ii,]) | is.na(traits_j_above[ii,]))[1]-1] # store corresponding trait for competitor
    dat_above$abundances_i_atTrait[ii] = abundances_i_above[ii, which(is.na(traits_i_above[ii,]) | is.na(traits_j_above[ii,]))[1]-1]
    dat_above$extinction_ij[ii] = 1 # set extinction for this rep to 1
    dat_above$ext_time_ij[ii] = which(is.na(traits_i_above[ii,]) | is.na(traits_j_above[ii,]))[1]-1
  }
  # if they both persist....
  if (!is.na(traits_i_above[ii,ncol(traits_i_above)]) & !is.na(traits_j_above[ii,ncol(traits_j_above)])){
    dat_above$trait_i[ii] = traits_i_above[ii, ncol(traits_i_above)] # store last trait value
    dat_above$trait_j[ii] = traits_j_above[ii, ncol(traits_j_above)] # store corresponding trait for competitor
    dat_above$abundances_i_atTrait[ii] = abundances_i_above[ii, ncol(traits_i_above)]
  }
}

# check
dat_above
names(dat_above)

# Plot final trait values against each other, 
### colored by final abundances where both competitors are present,
### facet wrapped by whether one competitor was extinct (Y/N) by tmax. ##
quartz(height = 4, width = 5) # doesn't work on windows
ggplot(dat_above, aes(x = trait_i, y = trait_j, color = abundances_i_atTmax)) +
  geom_point() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        aspect.ratio = 1) +
  ylab("Median maximum birth rate of\n competitor population") +
  xlab("Median maximum birth rate of\n focal population") +
  labs(color = "Focal population\nabundance at tmax") +
  facet_wrap(~extinction_ij, 
             labeller = labeller(extinction_ij = c("0" = "Neither Extinct",
                                                   "1" = "Focal or Competitor Extinct")))+
  ylim(0, 0.35) +
  xlim(0, 0.35) +
  geom_hline(yintercept= 0.25, lty = 2) + geom_vline(xintercept= 0.25, lty = 2)


#### Combined Plot for Figure 5 of MS ####
# For each dataframe created above, add an "InitEcol" variable that denotes which
# initial ecological state the simulations correspond to
dat$InitEcol = "Below"
dat_at$InitEcol = "At"
dat_above$InitEcol = "Above"

# rbind the dataframes for each initial state together into a single dataframe
dat_all = rbind(dat, dat_at, dat_above)
# relevel the InitEcol variable so that plots are in the same order as others in
# the manuscript (below, at, above)
dat_all$InitEcol = factor(dat_all$InitEcol, levels = c("Below", "At", "Above"))
# check
levels(dat_all$InitEcol)

# plot with facet_grid
quartz(height = 5, width = 8) # does not work on windows
ggplot(dat_all, aes(x = trait_i, y = trait_j, color = abundances_i_atTmax)) +
  geom_point() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        aspect.ratio = 1) +
  ylab(expression(paste("Maximum birth rate of competitor population ",
                            italic("j"),
                            ", ",
                            italic(b[max[j]])))) +
  xlab(expression(paste("Maximum birth rate of focal population ",
                            italic("i"),
                            ", ",
                            italic(b[max[i]])))) +
  labs(color = expression(paste(italic(N[i]),
                                "(",
                                italic(t[max]),
                                ")"))) +
  facet_grid(extinction_ij ~ rev(InitEcol), 
             labeller = labeller(extinction_ij = c("0" = "Neither Extinct",
                                                   "1" = "Focal or Competitor Extinct"))) +
  ylim(0, 0.35) +
  xlim(0, 0.35) +
  geom_hline(yintercept= 0.25, lty = 2) + geom_vline(xintercept= 0.25, lty = 2)
